### ISSUE TITLE
Using this without multimc?

### ISSUE THREAD

**Issue by Sir-Will** [jkoelndorfer/mccdl#10]
hey,
is it possible to use this to download a modpack without it creating a multimc instance?

**Comment by jkoelndorfer** [comment]
No, it's not possible. mccdl depends on MultiMC to download the correct version of Minecraft and Forge.

**Comment by Sir-Will** [comment]
I don't need forge or minecraft, only the mods. After testing 3 other downloaders this one is the only one with this feature:

> - If a manifest references a mod version that no longer exists on Curse, mccdl will find the next published file from the same mod (and Minecraft verseion) and download that, instead.

**Comment by jkoelndorfer** [comment]
Two things here:

* The development version of MultiMC supports importing Curse packs. It actually does the correct thing and pulls the archived mod version (mccdl does not do that). You could use that and pull the mods out of the MultiMC instance.
* You could use mccdl to run the download and pull the mods out of the created MultiMC instance.

(Also, you don't actually need MultiMC installed to use this).

**Comment by Sir-Will** [comment]
Would that work without the GUI? I would like to use it on a ubuntu server.

**Comment by jkoelndorfer** [comment]
Yes, that should work. I have run into some previous issues where the mccdl would fail if your MultiMC directory didn't exist. Please report this as a bug if you encounter it.

**Comment by Sir-Will** [comment]
Yep, got this error:
```
INFO:mccdl.MultiMcInstance:Creating MultiMC instance test, Minecraft version 1.7.10, Forge version 10.13.4.1492
Traceback (most recent call last):
  File "./mccdl.py", line 525, in <module>
    MccdlCommandLineApplication().run(sys.argv[1:])
  File "./mccdl.py", line 387, in run
    action_method(project_id, file_id, args.instance_name)
  File "./mccdl.py", line 71, in install_modpack
    self._setup_modpack("install", project_id, file_id, instance_name)
  File "./mccdl.py", line 99, in _setup_modpack
    setup_method(*setup_args)
  File "./mccdl.py", line 435, in create
    icon_path, os.path.join(self.instance_manager.multimc_directory, "icons", multimc_icon_filename)
  File "/home/mcgen/dev/SirWill/curse/.venv/lib/python3.5/shutil.py", line 115, in copyfile
    with open(dst, 'wb') as fdst:
FileNotFoundError: [Errno 2] No such file or directory: '/home/mcgen/.local/share/multimc5/icons/mccdl_635580589712293025.png'
```
Any way to define the instance destination?
