### ISSUE TITLE
Download of newer forge version fails/MultiMC API change

### ISSUE THREAD

**Issue by catt0** [jkoelndorfer/mccdl#11]
Downloading of newer forge versions fails (log at [1]). This seems to happen because MultiMC does not include forge versions 14.23.2.* in the old API (v0) at [2]. Switching to the v1 API [3] fixes this. At a glance the only API difference is the removal of "parentUid": "net.minecraft", at the beginning of the JSON.

Modifying the URL at [4] fixes this. As a test I changed the URL and downloaded a recent (Modern Skyblock 3, did not work before), an older (Project Ozone 2 Reloaded) and an old (Agrarian Skies) modpack. All but the last work, the last one fails due to a missing mod (bdlib), but forge is downloaded correctly.

[1] https://gist.github.com/catt0/4c39942989d3bc99f0fab188294b2960
[2] https://meta.multimc.org/net.minecraftforge/
[3] https://v1.meta.multimc.org/net.minecraftforge/
[4] https://github.com/jkoelndorfer/mccdl/blob/master/mccdl.py#L410

P.S. thank you for the downloader, after this fix it works where the others I tried failed!

**Comment by jkoelndorfer** [comment]
Thank you for submitting this @catt0. Let me also commend you for a concise and detailed issue report! Would you be willing to open this as a pull request so you get proper credit in the commit log for the fix? I will do a quick test on my end but I should be able to turn a merge around here pretty quick.

As you may be able to tell by the lack of commit history I have not been using this tool recently. I am glad you have found some use for it! :-)

**Comment by catt0** [comment]
Just did and thanks for the chance :)
