### ISSUE TITLE
Cannot install modpacks

### ISSUE THREAD

**Issue by GandalfTheHobbit** [jkoelndorfer/mccdl#5]
When I try to run it with the command:
> ./mccdl https://mods.curse.com/modpacks/minecraft/245163-ftb-presents-skyfactory-2-5 SkyFactory2.5

I get the following error:

> INFO:mccdl.CurseForgeClient:Installing modpack 245163 in instance SkyFactory2.5, file ID latest
> INFO:mccdl.CurseForgeProject:Fetching project 245163, file latest
> Traceback (most recent call last):
>   File "./mccdl.py", line 525, in <module>
>     MccdlCommandLineApplication().run(sys.argv[1:])
>   File "./mccdl.py", line 389, in run
>     action_method(project_id, file_id, args.instance_name)
>   File "./mccdl.py", line 73, in install_modpack
>     self._setup_modpack("install", project_id, file_id, instance_name)
>   File "./mccdl.py", line 92, in _setup_modpack
>     modpack_extract_dir = project.download_and_unpack_file(file_id)
>   File "./mccdl.py", line 142, in download_and_unpack_file
>     archive_path = self.download_file(file_id)
>   File "./mccdl.py", line 149, in download_file
>     file_path = self._client.downloader.download(self.file_url(file_id), destination)
>   File "./mccdl.py", line 279, in download
>     if os.path.exists(url_cache_path):
>   File "/home/aaron/MultiMC/mccdl-master/.venv/lib/python3.5/genericpath.py", line 19, in exists
>     os.stat(path)
> TypeError: argument should be string, bytes or integer, not PosixPath

MultiMC version: 0.5.0-887
I have got all of the necessary python packages, and I have ran it with and without sudo

**Comment by jkoelndorfer** [comment]
Thanks for the report. I'll try and get a fix out for this tonight.

In the interim, using Python 3.6 may get you going.

**Comment by GandalfTheHobbit** [comment]
I've updated to 3.6, and now I'm getting this error:

> python3: error while loading shared libraries: libpython3.5m.so.1.0: cannot open shared object file: No such file or directory

**Comment by jkoelndorfer** [comment]
How did you upgrade to Python 3.6? Something broke somewhere, and your Python is not working correctly. :-(

**Comment by GandalfTheHobbit** [comment]
I did yaourt -S python, and it upgraded it. Have I broken it? :(

**Comment by jkoelndorfer** [comment]
Ah, on Arch. Upgrading packages one-off like that is not advised, `pacman -Syu` and try again.

**Comment by jkoelndorfer** [comment]
Also - now that I'm looking at it, that's a 1.7.10 pack. I have an open bug for issues downloading 1.7.10 packs. I am going to work on getting that fixed, too.

**Comment by GandalfTheHobbit** [comment]
I have updated all my packages, and I still get the same error. It doesnt work with FTB Beyond either, a 1.10.2 pack

**Comment by jkoelndorfer** [comment]
I think now your virtualenv is still using an old python, so try removing it: `rm -rf .venv` from within the mccdl directory. Then rerun with Beyond - that *should* work.

I appreciate you pointing out these issues, I'll do my best to get them fixed quickly.

**Comment by GandalfTheHobbit** [comment]
Well, it kind of installed but it give me an error at the end:

> Traceback (most recent call last):
>   File "./mccdl.py", line 525, in <module>
>     MccdlCommandLineApplication().run(sys.argv[1:])
>   File "./mccdl.py", line 389, in run
>     action_method(project_id, file_id, args.instance_name)
>   File "./mccdl.py", line 73, in install_modpack
>     self._setup_modpack("install", project_id, file_id, instance_name)
>   File "./mccdl.py", line 101, in _setup_modpack
>     setup_method(*setup_args)
>   File "./mccdl.py", line 436, in create
>     shutil.copyfile(icon_path, self.instance_manager.multimc_directory / "icons" / multimc_icon_filename)
>   File "/home/aaron/MultiMC/mccdl-master/.venv/lib/python3.6/shutil.py", line 115, in copyfile
>     with open(dst, 'wb') as fdst:
> FileNotFoundError: [Errno 2] No such file or directory: '/home/aaron/.local/share/multimc5/icons/mccdl_636237984038792137.png'

It's getting close though!

**Comment by jkoelndorfer** [comment]
OK - that looks to me like the MultiMC directory doesn't exist, which means you either haven't launched it or it's in a different location than on my system.

My MultiMC directory is `~/.local/share/multimc5`, which is the default as far as I know. Where is yours? You can specify it by passing an additional argument `--multimc-directory=/path/to/multimc` which should be the directory that contains these files:

    % ls ~/.local/share/multimc5
    accounts  icons  instances  libraries  mods  themes  translations  versions  accounts.json  metacache  MultiMC-0.log  MultiMC-1.log  MultiMC-2.log  MultiMC-3.log  MultiMC-4.log  multimc.cfg

**Comment by GandalfTheHobbit** [comment]
I think it's working: it's downloading the files into the right folders. Thanks for all the help!

**Comment by jkoelndorfer** [comment]
I appreciate the help testing - please let me know if you are able to launch FTB Beyond successfully. That's a pack that I tested on my system, so it better work. :-)

**Comment by GandalfTheHobbit** [comment]
Uh, I could boot but it crashes, and I'm not sure if it's due to mccdl or just the modpack. This is the log, if you can find anything from that: https://pastebin.com/4JfcqzLA

This log might help too: https://pastebin.com/68WpRFWJ (I posted the wrong log)

**Comment by jkoelndorfer** [comment]
That error looks to be related to OpenGL, so not a `mccdl` bug. Maybe you don't have your graphics drivers installed? That might be something to check with https://www.reddit.com/r/feedthebeast on.

**Comment by GandalfTheHobbit** [comment]
I've updated my nvidia drivers, and it boots now! Thanks for all the help

**Comment by GandalfTheHobbit** [comment]
I just found a new bug while trying to install Project Ozone 2. Whenever I try to install it, I get this error in console: https://pastebin.com/wRMPH80k

**Comment by jkoelndorfer** [comment]
We're dealing with two different issues now - can you open another issue for this one?
